import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({
  variable: "--font-inter", // Tailwind veya CSS değişkenleriyle kullanım
  display: "swap", // "auto", "block", "swap", "fallback", "optional"
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"], // Tüm font ağırlıkları
  style: ["normal", "italic"], // Normal ve italik stiller
  subsets: ["latin", "latin-ext"], // Geniş kapsamlı karakter seti
  preload: true, // Performans için preloading (true varsayılan)
});

export const metadata: Metadata = {
  title: "Taskflow",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="bg-primary-dark">
      <body className={`${inter.variable} antialiased`}>{children}</body>
    </html>
  );
}
