import type { Metadata } from "next";
import DashboardLayout from "./dashboard-layout";

export const metadata: Metadata = {
  title: "Taskflow",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return <DashboardLayout>{children}</DashboardLayout>;
}
